/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diozero_internal_provider_builtin_gpio_NativeGpioDevice */

#ifndef _Included_com_diozero_internal_provider_builtin_gpio_NativeGpioDevice
#define _Included_com_diozero_internal_provider_builtin_gpio_NativeGpioDevice
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_diozero_internal_provider_builtin_gpio_NativeGpioDevice
 * Method:    getChips
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_diozero_internal_provider_builtin_gpio_NativeGpioDevice_getChips
  (JNIEnv *, jclass);

/*
 * Class:     com_diozero_internal_provider_builtin_gpio_NativeGpioDevice
 * Method:    openChip
 * Signature: (Ljava/lang/String;)Lcom/diozero/internal/provider/builtin/gpio/GpioDeviceChip;
 */
JNIEXPORT jobject JNICALL Java_com_diozero_internal_provider_builtin_gpio_NativeGpioDevice_openChip
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_diozero_internal_provider_builtin_gpio_NativeGpioDevice
 * Method:    provisionGpioInputDevice
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_builtin_gpio_NativeGpioDevice_provisionGpioInputDevice
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_diozero_internal_provider_builtin_gpio_NativeGpioDevice
 * Method:    provisionGpioOutputDevice
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_builtin_gpio_NativeGpioDevice_provisionGpioOutputDevice
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_diozero_internal_provider_builtin_gpio_NativeGpioDevice
 * Method:    getValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_builtin_gpio_NativeGpioDevice_getValue
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_diozero_internal_provider_builtin_gpio_NativeGpioDevice
 * Method:    setValue
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_builtin_gpio_NativeGpioDevice_setValue
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_diozero_internal_provider_builtin_gpio_NativeGpioDevice
 * Method:    epollCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_builtin_gpio_NativeGpioDevice_epollCreate
  (JNIEnv *, jclass);

/*
 * Class:     com_diozero_internal_provider_builtin_gpio_NativeGpioDevice
 * Method:    epollAddFileDescriptor
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_builtin_gpio_NativeGpioDevice_epollAddFileDescriptor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_diozero_internal_provider_builtin_gpio_NativeGpioDevice
 * Method:    epollRemoveFileDescriptor
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_builtin_gpio_NativeGpioDevice_epollRemoveFileDescriptor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_diozero_internal_provider_builtin_gpio_NativeGpioDevice
 * Method:    eventLoop
 * Signature: (IILcom/diozero/internal/provider/builtin/gpio/GpioLineEventListener;)V
 */
JNIEXPORT void JNICALL Java_com_diozero_internal_provider_builtin_gpio_NativeGpioDevice_eventLoop
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_diozero_internal_provider_builtin_gpio_NativeGpioDevice
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_diozero_internal_provider_builtin_gpio_NativeGpioDevice_close
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
