/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diozero_internal_provider_sysfs_NativeSerialDevice */

#ifndef _Included_com_diozero_internal_provider_sysfs_NativeSerialDevice
#define _Included_com_diozero_internal_provider_sysfs_NativeSerialDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_diozero_internal_provider_sysfs_NativeSerialDevice
 * Method:    serialOpen
 * Signature: (Ljava/lang/String;IIII)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_diozero_internal_provider_sysfs_NativeSerialDevice_serialOpen
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeSerialDevice
 * Method:    serialConfigPort
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeSerialDevice_serialConfigPort
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeSerialDevice
 * Method:    serialReadByte
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeSerialDevice_serialReadByte
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeSerialDevice
 * Method:    serialWriteByte
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeSerialDevice_serialWriteByte
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeSerialDevice
 * Method:    serialRead
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeSerialDevice_serialRead
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeSerialDevice
 * Method:    serialWrite
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeSerialDevice_serialWrite
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeSerialDevice
 * Method:    serialBytesAvailable
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeSerialDevice_serialBytesAvailable
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeSerialDevice
 * Method:    serialClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeSerialDevice_serialClose
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
