/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus */

#ifndef _Included_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
#define _Included_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    smbusOpen
 * Signature: (Ljava/lang/String;IZ)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_smbusOpen(
		JNIEnv* env, jclass clz, jstring i2cAdapter, jint deviceAddress, jboolean force);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    getFuncs
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_getFuncs(
		JNIEnv* env, jclass clz, jint fd);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    smbusClose
 * Signature: (I)
 */
JNIEXPORT void JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_smbusClose(
		JNIEnv* env, jclass clz, jint fd);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    writeQuick
 * Signature: (IB)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_writeQuick(
		JNIEnv* env, jclass clz, jint fd, jbyte value);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    readByte
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_readByte(
		JNIEnv* env, jclass clz, jint fd);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    writeByte
 * Signature: (IB)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_writeByte(
		JNIEnv* env, jclass clz, jint fd, jbyte value);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    readBytes
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_readBytes(
		JNIEnv* env, jclass clz, jint fd, jint rxLength, jbyteArray rxData);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    writeBytes
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_writeBytes(
		JNIEnv* env, jclass clz, jint fd, jint txLength, jbyteArray txData);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    readByteData
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_readByteData(
		JNIEnv* env, jclass clz, jint fd, jint registerAddress);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    writeByteData
 * Signature: (IIB)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_writeByteData(
		JNIEnv* env, jclass clz, jint fd, jint registerAddress, jbyte value);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    readWordData
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_readWordData(
		JNIEnv* env, jclass clz, jint fd, jint registerAddress);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    writeWordData
 * Signature: (IIS)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_writeWordData(
		JNIEnv* env, jclass clz, jint fd, jint registerAddress, jshort value);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    processCall
 * Signature: (IIS)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_processCall(
		JNIEnv* env, jclass clz, jint fd, jint registerAddress, jshort value);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    readBlockData
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_readBlockData(
		JNIEnv* env, jclass clz, jint fd, jint registerAddress, jbyteArray rxData);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    writeBlockData
 * Signature: (III[B)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_writeBlockData(
		JNIEnv* env, jclass clz, jint fd, jint registerAddress, jint txLength, jbyteArray txData);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    readI2CBlockData
 * Signature: (III[B)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_readI2CBlockData(
		JNIEnv* env, jclass clz, jint fd, jint registerAddress, jint rxLength, jbyteArray rxData);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    writeI2CBlockData
 * Signature: (III[B)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_writeI2CBlockData(
		JNIEnv* env, jclass clz, jint fd, jint registerAddress, jint txLength, jbyteArray txData);

/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus
 * Method:    blockProcessCall
 * Signature: (III[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSMBus_blockProcessCall(
		JNIEnv* env, jclass clz, jint fd, jint registerAddress, jint txLength, jbyteArray txData, jbyteArray rxData);

#ifdef __cplusplus
}
#endif
#endif
