/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diozero_internal_provider_sysfs_NativeSysFsI2C */

#ifndef _Included_com_diozero_internal_provider_sysfs_NativeSysFsI2C
#define _Included_com_diozero_internal_provider_sysfs_NativeSysFsI2C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_diozero_internal_provider_sysfs_NativeSysFsI2C
 * Method:    selectSlave
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeSysFsI2C_selectSlave
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
