/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diozero_internal_provider_sysfs_NativeI2CDeviceSysFs */

#ifndef _Included_com_diozero_internal_provider_sysfs_NativeI2CDeviceSysFs
#define _Included_com_diozero_internal_provider_sysfs_NativeI2CDeviceSysFs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_diozero_internal_provider_sysfs_NativeI2CDeviceSysFs
 * Method:    selectSlave
 * Signature: (IIZ)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_sysfs_NativeI2CDeviceSysFs_selectSlave(
		JNIEnv* env, jclass clz, jint fd, jint deviceAddress, jboolean force);

#ifdef __cplusplus
}
#endif
#endif
