/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diozero_util_SleepUtil */

#ifndef _Included_com_diozero_util_SleepUtil
#define _Included_com_diozero_util_SleepUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef com_diozero_util_SleepUtil_MS_IN_SEC
#define com_diozero_util_SleepUtil_MS_IN_SEC 1000L
#undef com_diozero_util_SleepUtil_US_IN_SEC
#define com_diozero_util_SleepUtil_US_IN_SEC 1000000LL
#undef com_diozero_util_SleepUtil_NS_IN_SEC
#define com_diozero_util_SleepUtil_NS_IN_SEC 1000000000LL
#undef com_diozero_util_SleepUtil_NS_IN_US
#define com_diozero_util_SleepUtil_NS_IN_US 1000L
#undef com_diozero_util_SleepUtil_US_IN_MS
#define com_diozero_util_SleepUtil_US_IN_MS 1000L
#undef com_diozero_util_SleepUtil_NS_IN_MS
#define com_diozero_util_SleepUtil_NS_IN_MS 1000000LL
/*
 * Class:     com_diozero_util_SleepUtil
 * Method:    sleepNanos
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_com_diozero_util_SleepUtil_sleepNanos
  (JNIEnv *, jclass, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
