/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diozero_internal_provider_builtin_serial_NativeSerialDevice */

#ifndef _Included_com_diozero_internal_provider_builtin_serial_NativeSerialDevice
#define _Included_com_diozero_internal_provider_builtin_serial_NativeSerialDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_diozero_internal_provider_builtin_serial_NativeSerialDevice
 * Method:    serialOpen
 * Signature: (Ljava/lang/String;IIIIZII)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_diozero_internal_provider_builtin_serial_NativeSerialDevice_serialOpen
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jboolean, jint, jint);

/*
 * Class:     com_diozero_internal_provider_builtin_serial_NativeSerialDevice
 * Method:    serialConfigPort
 * Signature: (IIIIIZII)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_builtin_serial_NativeSerialDevice_serialConfigPort
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jboolean, jint, jint);

/*
 * Class:     com_diozero_internal_provider_builtin_serial_NativeSerialDevice
 * Method:    serialClose
 * Signature: (Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_builtin_serial_NativeSerialDevice_serialClose
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
