/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diozero_util_MmapBufferNative */

#ifndef _Included_com_diozero_util_MmapBufferNative
#define _Included_com_diozero_util_MmapBufferNative
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_com_diozero_util_MmapBufferNative_createMmapBuffer
  (JNIEnv *, jclass, jstring, jint, jint);

JNIEXPORT void JNICALL Java_com_diozero_util_MmapBufferNative_closeMmapBuffer
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
