/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diozero_util_FileNative */

#ifndef _Included_com_diozero_util_FileNative
#define _Included_com_diozero_util_FileNative
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_diozero_util_FileNative
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_util_FileNative_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_diozero_util_FileNative
 * Method:    addFile
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_util_FileNative_close
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
