/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diozero_util_PollNative */

#ifndef _Included_com_diozero_util_PollNative
#define _Included_com_diozero_util_PollNative
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_diozero_util_PollNative
 * Method:    poll
 * Signature: ()I
 */
JNIEXPORT void JNICALL Java_com_diozero_util_PollNative_poll
  (JNIEnv *, jobject, jstring, jint, jint, jobject);

/*
 * Class:     com_diozero_util_PollNative
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT void JNICALL Java_com_diozero_util_PollNative_stop
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
