/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diozero_util_MmapBufferNative */

#ifndef _Included_com_diozero_util_MmapBufferNative
#define _Included_com_diozero_util_MmapBufferNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_diozero_util_MmapBufferNative
 * Method:    createMmapBuffer
 * Signature: (Ljava/lang/String;JJ)Lcom/diozero/util/MmapByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_diozero_util_MmapBufferNative_createMmapBuffer
  (JNIEnv *, jclass, jstring, jlong, jlong);

/*
 * Class:     com_diozero_util_MmapBufferNative
 * Method:    closeMmapBuffer
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_diozero_util_MmapBufferNative_closeMmapBuffer
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
