/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diozero_internal_provider_jpi_JPiNative */

#ifndef _Included_com_diozero_internal_provider_jpi_JPiNative
#define _Included_com_diozero_internal_provider_jpi_JPiNative
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_com_diozero_internal_provider_jpi_JPiNative_createMmapBuffer
  (JNIEnv *, jclass, jstring, jint, jint);

JNIEXPORT void JNICALL Java_com_diozero_internal_provider_jpi_JPiNative_closeMmapBuffer
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
