/*-
 * #%L
 * Organisation: diozero
 * Project:      Device I/O Zero - Remote Server
 * Filename:     diozero.pb.c  
 * 
 * This file is part of the diozero project. More information about this project
 * can be found at http://www.diozero.com/
 * %%
 * Copyright (C) 2016 - 2021 diozero
 * %%
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * #L%
 */

/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "src/main/proto/diozero.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(diozero_MessageWrapper, diozero_MessageWrapper, AUTO)


PB_BIND(diozero_Response, diozero_Response, AUTO)


PB_BIND(diozero_Gpio, diozero_Gpio, AUTO)


PB_BIND(diozero_Gpio_GpioInfo, diozero_Gpio_GpioInfo, AUTO)


PB_BIND(diozero_Gpio_GetBoardInfo, diozero_Gpio_GetBoardInfo, AUTO)


PB_BIND(diozero_Gpio_GetBoardInfoResponse, diozero_Gpio_GetBoardInfoResponse, AUTO)


PB_BIND(diozero_Gpio_ProvisionDigitalInput, diozero_Gpio_ProvisionDigitalInput, AUTO)


PB_BIND(diozero_Gpio_ProvisionDigitalOutput, diozero_Gpio_ProvisionDigitalOutput, AUTO)


PB_BIND(diozero_Gpio_ProvisionDigitalInputOutput, diozero_Gpio_ProvisionDigitalInputOutput, AUTO)


PB_BIND(diozero_Gpio_ProvisionPwmOutput, diozero_Gpio_ProvisionPwmOutput, AUTO)


PB_BIND(diozero_Gpio_ProvisionAnalogInput, diozero_Gpio_ProvisionAnalogInput, AUTO)


PB_BIND(diozero_Gpio_ProvisionAnalogOutput, diozero_Gpio_ProvisionAnalogOutput, AUTO)


PB_BIND(diozero_Gpio_DigitalRead, diozero_Gpio_DigitalRead, AUTO)


PB_BIND(diozero_Gpio_DigitalWrite, diozero_Gpio_DigitalWrite, AUTO)


PB_BIND(diozero_Gpio_PwmRead, diozero_Gpio_PwmRead, AUTO)


PB_BIND(diozero_Gpio_PwmWrite, diozero_Gpio_PwmWrite, AUTO)


PB_BIND(diozero_Gpio_AnalogRead, diozero_Gpio_AnalogRead, AUTO)


PB_BIND(diozero_Gpio_AnalogWrite, diozero_Gpio_AnalogWrite, AUTO)


PB_BIND(diozero_Gpio_Events, diozero_Gpio_Events, AUTO)


PB_BIND(diozero_Gpio_Close, diozero_Gpio_Close, AUTO)


PB_BIND(diozero_Gpio_DigitalReadResponse, diozero_Gpio_DigitalReadResponse, AUTO)


PB_BIND(diozero_Gpio_PwmReadResponse, diozero_Gpio_PwmReadResponse, AUTO)


PB_BIND(diozero_Gpio_AnalogReadResponse, diozero_Gpio_AnalogReadResponse, AUTO)


PB_BIND(diozero_Gpio_Notification, diozero_Gpio_Notification, AUTO)


PB_BIND(diozero_I2C, diozero_I2C, AUTO)


PB_BIND(diozero_I2C_Open, diozero_I2C_Open, AUTO)


PB_BIND(diozero_I2C_ReadByte, diozero_I2C_ReadByte, AUTO)


PB_BIND(diozero_I2C_WriteByte, diozero_I2C_WriteByte, AUTO)


PB_BIND(diozero_I2C_Read, diozero_I2C_Read, AUTO)


PB_BIND(diozero_I2C_Write, diozero_I2C_Write, AUTO)


PB_BIND(diozero_I2C_ReadByteData, diozero_I2C_ReadByteData, AUTO)


PB_BIND(diozero_I2C_WriteByteData, diozero_I2C_WriteByteData, AUTO)


PB_BIND(diozero_I2C_ReadI2CBlockData, diozero_I2C_ReadI2CBlockData, AUTO)


PB_BIND(diozero_I2C_WriteI2CBlockData, diozero_I2C_WriteI2CBlockData, AUTO)


PB_BIND(diozero_I2C_Close, diozero_I2C_Close, AUTO)


PB_BIND(diozero_I2C_ReadByteResponse, diozero_I2C_ReadByteResponse, AUTO)


PB_BIND(diozero_I2C_ReadResponse, diozero_I2C_ReadResponse, AUTO)


PB_BIND(diozero_Spi, diozero_Spi, AUTO)


PB_BIND(diozero_Spi_Open, diozero_Spi_Open, AUTO)


PB_BIND(diozero_Spi_Write, diozero_Spi_Write, AUTO)


PB_BIND(diozero_Spi_WriteAndRead, diozero_Spi_WriteAndRead, AUTO)


PB_BIND(diozero_Spi_Close, diozero_Spi_Close, AUTO)


PB_BIND(diozero_Spi_SpiResponse, diozero_Spi_SpiResponse, AUTO)








