/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diozero_internal_provider_bbbiolib_BbbIoLibNative */

#ifndef _Included_com_diozero_internal_provider_bbbiolib_BbbIoLibNative
#define _Included_com_diozero_internal_provider_bbbiolib_BbbIoLibNative
#ifdef __cplusplus
extern "C" {
#endif
#undef com_diozero_internal_provider_bbbiolib_BbbIoLibNative_BBBIO_DIR_IN
#define com_diozero_internal_provider_bbbiolib_BbbIoLibNative_BBBIO_DIR_IN 0L
#undef com_diozero_internal_provider_bbbiolib_BbbIoLibNative_BBBIO_DIR_OUT
#define com_diozero_internal_provider_bbbiolib_BbbIoLibNative_BBBIO_DIR_OUT 1L
/*
 * Class:     com_diozero_internal_provider_bbbiolib_BbbIoLibNative
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_bbbiolib_BbbIoLibNative_init
  (JNIEnv *, jclass);

/*
 * Class:     com_diozero_internal_provider_bbbiolib_BbbIoLibNative
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_diozero_internal_provider_bbbiolib_BbbIoLibNative_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_diozero_internal_provider_bbbiolib_BbbIoLibNative
 * Method:    setDir
 * Signature: (BBB)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_bbbiolib_BbbIoLibNative_setDir
  (JNIEnv *, jclass, jbyte, jbyte, jbyte);

/*
 * Class:     com_diozero_internal_provider_bbbiolib_BbbIoLibNative
 * Method:    getValue
 * Signature: (BB)I
 */
JNIEXPORT jint JNICALL Java_com_diozero_internal_provider_bbbiolib_BbbIoLibNative_getValue
  (JNIEnv *, jclass, jbyte, jbyte);

/*
 * Class:     com_diozero_internal_provider_bbbiolib_BbbIoLibNative
 * Method:    setValue
 * Signature: (BBZ)I
 */
JNIEXPORT void JNICALL Java_com_diozero_internal_provider_bbbiolib_BbbIoLibNative_setValue
  (JNIEnv *, jclass, jbyte, jbyte, jboolean);

#ifdef __cplusplus
}
#endif
#endif
