/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diozero_ws281xj_WS281xNative */

#ifndef _Included_com_diozero_ws281xj_WS281xNative
#define _Included_com_diozero_ws281xj_WS281xNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_diozero_ws281xj_WS281xNative
 * Method:    initialise
 * Signature: (IIIIII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_diozero_ws281xj_WS281xNative_initialise
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_diozero_ws281xj_WS281xNative
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_diozero_ws281xj_WS281xNative_terminate
  (JNIEnv *, jclass);

/*
 * Class:     com_diozero_ws281xj_WS281xNative
 * Method:    render
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_diozero_ws281xj_WS281xNative_render
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
