/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GpioMMapTest */

#ifndef _Included_GpioMMapTest
#define _Included_GpioMMapTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GpioMMapTest
 * Method:    initialise
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_GpioMMapTest_initialise
  (JNIEnv *, jclass, jint);

/*
 * Class:     GpioMMapTest
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GpioMMapTest_terminate
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
