/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GpioMMapTest */

#ifndef _Included_GpioMMapTest
#define _Included_GpioMMapTest
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_GpioMMapTest_createMmapBuffer
  (JNIEnv *, jclass, jstring, jint, jint);

JNIEXPORT void JNICALL Java_GpioMMapTest_closeMmapBuffer
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
